# This is only to create-account a GitHub release
name: GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  pre-release:
    name: Create Pre-Release
    if: "contains(github.ref, 'beta')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2

      - name: Get Release Notes
        id: get_release_notes
        uses: yashanand1910/standard-release-notes@v1.2.0
        with:
          version: ${{ github.ref }}

      - name: Create
        id: create_prerelease
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.get_release_notes.outputs.release_notes }}
          prerelease: true

  release:
    name: Create Release
    if: "!contains(github.ref, 'beta')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2

      - name: Get Release Notes
        id: get_release_notes
        uses: yashanand1910/standard-release-notes@v1.2.0
        with:
          version: ${{ github.ref }}

      - name: Create
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.get_release_notes.outputs.release_notes }}
          prerelease: false
